Q3. Singular Value Decomposition (SVD):


In [ ]:
import numpy as np

# Set random seed
np.random.seed(31)

# Create a random 5x5 matrix A with integers between 0 and 9
A = np.random.randint(0, 10, size=(5, 5))

print("Original Matrix A:")
print(A)

Original Matrix A:
[[2 7 0 2 7]
 [6 6 2 2 9]
 [1 7 1 1 4]
 [6 3 3 2 8]
 [7 8 1 4 8]]


In [ ]:
# Perform Singular Value Decomposition (SVD)
U, S, Vt = np.linalg.svd(A)

# Construct Σ matrix
Sigma = np.zeros_like(A, dtype=float)
Sigma[:min(A.shape), :min(A.shape)] = np.diag(S)

# Print U, Σ, and Vt matrices
print("\nMatrix U:")
print(U)
print("\nMatrix Σ:")
print(Sigma)
print("\nMatrix Vt:")
print(Vt)

# Verify that A equals the product of U, Σ, and Vt
A_reconstructed = np.dot(U, np.dot(Sigma, Vt))
print("\nReconstructed Matrix A:")
print(A_reconstructed)

# Rank 2 approximation of matrix A
rank_2_approximation = np.dot(U[:, :2], np.dot(Sigma[:2, :2], Vt[:2, :]))
print("\nRank 2 Approximation of Matrix A:")
print(rank_2_approximation)

# Rank 3 approximation of matrix A
rank_3_approximation = np.dot(U[:, :3], np.dot(Sigma[:3, :3], Vt[:3, :]))
print("\nRank 3 Approximation of Matrix A:")
print(rank_3_approximation)


Matrix U:
[[-0.39953091  0.45674837  0.32361638 -0.68666455 -0.23562728]
 [-0.51144075 -0.21832159  0.24795802 -0.00299073  0.79326662]
 [-0.29741327  0.6070015   0.2045938   0.70273809 -0.08599468]
 [-0.42189049 -0.6124601   0.33881141  0.18504213 -0.54577218]
 [-0.55888923  0.01258615 -0.82288363 -0.02003592 -0.09972716]]

Matrix Σ:
[[24.63415922  0.          0.          0.          0.        ]
 [ 0.          5.89886419  0.          0.          0.        ]
 [ 0.          0.          2.56033529  0.          0.        ]
 [ 0.          0.          0.          1.57457159  0.        ]
 [ 0.          0.          0.          0.          0.57184643]]

Matrix Vt:
[[-0.43064945 -0.5554904  -0.12766238 -0.211036   -0.66718632]
 [-0.57232864  0.74584331 -0.28046685 -0.01537933 -0.19302723]
 [-0.54201585 -0.14897092  0.34919662 -0.49453255  0.56349424]
 [ 0.17875717  0.31082067  0.78233795 -0.24554736 -0.44619526]
 [ 0.40155406  0.12785282 -0.41358157 -0.80645604 -0.03141549]]

Reconstructed Mat